import type { Game } from "@/constants/games";

export type PrototypePlayer = {
  id: string;
  handle: string;
  realName: string;
  country: string;
  countryCode: string;
  team?: string;
  game: Game;
  role: string;
  rank: number;
  score: number;
  trend: number;
  identity: string;
  aura: string;
  bestMap: string;
  strengths: string[];
  weakness: string;
  summary: string;
  playstyle: string;
  oneYearScore: number[];
};

/**
 * Local prototype records carried forward from the original Players experience.
 * These values are presentation fixtures, not methodology-approved rankings.
 */
export const prototypePlayers: readonly PrototypePlayer[] = [
  {
    id: "northstar-mika",
    handle: "Northstar",
    realName: "Mika Larsen",
    country: "Denmark",
    countryCode: "dk",
    game: "CS2",
    role: "IGL",
    rank: 1,
    score: 98,
    trend: 2,
    identity: "Tactical Brain",
    aura: "The Compass",
    bestMap: "Ancient",
    strengths: ["Mid-round calling", "Utility discipline", "Team structure"],
    weakness: "Low opening duel frequency",
    summary: "Turns messy CS2 rounds into clean geometry, making the whole team feel one second ahead.",
    playstyle: "Slow information gathering, sharp late-round calls, and calm utility layering.",
    oneYearScore: [88, 90, 91, 93, 94, 96, 97, 98],
  },
  {
    id: "vanta-seo",
    handle: "Vanta",
    realName: "Seo Min-jun",
    country: "South Korea",
    countryCode: "kr",
    game: "League of Legends",
    role: "Mid Laner",
    rank: 2,
    score: 97,
    trend: 1,
    identity: "Mechanical Demon",
    aura: "The Machine Ghost",
    bestMap: "Summoner's Rift",
    strengths: ["Lane control", "Micro spacing", "Teamfight execution"],
    weakness: "Occasionally over-forces tempo",
    summary: "A precision mid laner with surgical mechanics and ruthless spacing punishment.",
    playstyle: "Dominant laning, wave control, and cold teamfight positioning.",
    oneYearScore: [91, 92, 93, 94, 95, 96, 97, 97],
  },
  {
    id: "carnaval-lucas",
    handle: "Carnaval",
    realName: "Lucas Rocha",
    country: "Brazil",
    countryCode: "br",
    game: "CS2",
    role: "Entry",
    rank: 3,
    score: 96,
    trend: 4,
    identity: "Chaos Agent",
    aura: "The Firework",
    bestMap: "Mirage",
    strengths: ["Opening duels", "Pressure swings", "Crowd momentum"],
    weakness: "High-risk decision making",
    summary: "A Brazilian entry who creates space by kicking the door off its hinges.",
    playstyle: "Fast contact, aggressive peeks, and momentum-heavy site explosions.",
    oneYearScore: [84, 86, 89, 90, 92, 94, 95, 96],
  },
  {
    id: "orbit-emily",
    handle: "Orbit",
    realName: "Emily Carter",
    country: "USA",
    countryCode: "us",
    game: "Fortnite",
    role: "Builder",
    rank: 4,
    score: 95,
    trend: 3,
    identity: "Creative Builder",
    aura: "The Architect",
    bestMap: "Endgame Zone",
    strengths: ["Piece control", "Layer swaps", "Endgame creativity"],
    weakness: "Early-game resource greed",
    summary: "Turns late circles into moving architecture and survives by making better shapes faster.",
    playstyle: "Creative tunnelling, quick retakes, and calm high-pressure endgames.",
    oneYearScore: [83, 85, 87, 89, 91, 93, 94, 95],
  },
  {
    id: "shiro-yuki",
    handle: "Shiro",
    realName: "Yuki Tanaka",
    country: "Japan",
    countryCode: "jp",
    game: "Valorant",
    role: "Duelist",
    rank: 5,
    score: 94,
    trend: 3,
    identity: "Ice-Cold Finisher",
    aura: "The Needle",
    bestMap: "Ascent",
    strengths: ["First contact", "Crosshair discipline", "Late-round calm"],
    weakness: "Needs space from initiators",
    summary: "A precise duelist with clean first bullets and unusually quiet retakes.",
    playstyle: "Measured entries, patient angle clearing, and disciplined multi-kill conversions.",
    oneYearScore: [82, 84, 86, 88, 90, 92, 93, 94],
  },
  {
    id: "nova-claire",
    handle: "Nova",
    realName: "Claire Dubois",
    country: "France",
    countryCode: "fr",
    game: "Rocket League",
    role: "Striker",
    rank: 6,
    score: 93,
    trend: 2,
    identity: "Momentum Player",
    aura: "The Comet",
    bestMap: "Champions Field",
    strengths: ["Aerial pressure", "Fast rotations", "Backboard reads"],
    weakness: "Can overcommit in streaks",
    summary: "A French striker who turns one clean touch into three seconds of panic.",
    playstyle: "High-tempo rotations, aerial challenges, and ruthless shot chaining.",
    oneYearScore: [84, 85, 87, 88, 90, 91, 92, 93],
  },
  {
    id: "hex-li",
    handle: "Hex",
    realName: "Li Wei",
    country: "China",
    countryCode: "cn",
    game: "League of Legends",
    role: "Jungler",
    rank: 7,
    score: 92,
    trend: -1,
    identity: "Macro Architect",
    aura: "The Mapmaker",
    bestMap: "Summoner's Rift",
    strengths: ["Pathing", "Objective trading", "Vision timing"],
    weakness: "Low-risk early game",
    summary: "A cerebral jungler who slowly tightens the map until every objective feels pre-owned.",
    playstyle: "Controlled pathing, objective maths, and suffocating vision control.",
    oneYearScore: [93, 93, 92, 92, 91, 92, 92, 92],
  },
  {
    id: "rune-oliver",
    handle: "Rune",
    realName: "Oliver Svensson",
    country: "Sweden",
    countryCode: "se",
    game: "CS2",
    role: "AWPer",
    rank: 8,
    score: 91,
    trend: -2,
    identity: "Clutch Artist",
    aura: "The Cold Scope",
    bestMap: "Nuke",
    strengths: ["Late-round reads", "AWP discipline", "1vX composure"],
    weakness: "Slower opening impact",
    summary: "A Swedish AWPer who seems most awake when everyone else is gone.",
    playstyle: "Patient AWPing, late-round repositioning, and composed clutch routes.",
    oneYearScore: [94, 93, 93, 92, 91, 91, 90, 91],
  },
  {
    id: "signal-aisha",
    handle: "Signal",
    realName: "Aisha Khan",
    country: "India",
    countryCode: "in",
    game: "Valorant",
    role: "Controller",
    rank: 9,
    score: 90,
    trend: 6,
    identity: "Team Anchor",
    aura: "The Relay",
    bestMap: "Bind",
    strengths: ["Smoke timing", "Post-plant stability", "Comms clarity"],
    weakness: "Needs more opening assertiveness",
    summary: "A controller who keeps frantic rounds stitched together and makes chaos readable.",
    playstyle: "Support-first control, late utility value, and clean information calls.",
    oneYearScore: [72, 76, 80, 83, 86, 88, 89, 90],
  },
  {
    id: "surge-benji",
    handle: "Surge",
    realName: "Benji O'Keefe",
    country: "Australia",
    countryCode: "au",
    game: "CS2",
    role: "Entry",
    rank: 10,
    score: 89,
    trend: 5,
    identity: "Momentum Player",
    aura: "The Outback Spark",
    bestMap: "Inferno",
    strengths: ["Tempo breaks", "Fearless entries", "Resilience"],
    weakness: "Occasional dry-peek addiction",
    summary: "An Australian entry with distance-fighter stubbornness and pub-brawl theatre.",
    playstyle: "Fast entries, risky pressure, and high-energy retake disruption.",
    oneYearScore: [70, 74, 78, 81, 84, 87, 88, 89],
  },
  {
    id: "voltage-murat",
    handle: "Voltage",
    realName: "Murat Yilmaz",
    country: "Turkey",
    countryCode: "tr",
    game: "Valorant",
    role: "Duelist",
    rank: 11,
    score: 88,
    trend: 5,
    identity: "Mechanical Demon",
    aura: "The Furnace",
    bestMap: "Haven",
    strengths: ["Raw aim", "Explosive entries", "Confidence spikes"],
    weakness: "Discipline when ahead",
    summary: "A Turkish duelist with furnace-hot aim and the confidence to make defenders feel hunted.",
    playstyle: "Explosive dashes, wide-swing pressure, and fast multi-frag attempts.",
    oneYearScore: [73, 76, 79, 82, 85, 86, 87, 88],
  },
  {
    id: "frost-mia",
    handle: "Frost",
    realName: "Mia Henderson",
    country: "Canada",
    countryCode: "ca",
    game: "Valorant",
    role: "Support",
    rank: 12,
    score: 87,
    trend: 3,
    identity: "Silent Carry",
    aura: "The Snowline",
    bestMap: "Lotus",
    strengths: ["Trade timing", "Utility layering", "Low-error rounds"],
    weakness: "Low highlight visibility",
    summary: "A quiet support who rarely tops clips but often wins the round before the duel starts.",
    playstyle: "Trade-first support, disciplined utility, and clean late-round spacing.",
    oneYearScore: [78, 79, 81, 83, 84, 85, 86, 87],
  },
  {
    id: "keystone-jonas",
    handle: "Keystone",
    realName: "Jonas Müller",
    country: "Germany",
    countryCode: "de",
    game: "Chess",
    role: "Strategist",
    rank: 13,
    score: 86,
    trend: 1,
    identity: "Tactical Brain",
    aura: "The Engineer",
    bestMap: "Sicilian Defence",
    strengths: ["Calculation", "Endgame technique", "Time management"],
    weakness: "Sharp gambit positions",
    summary: "A structured strategist who treats the board like an engine room.",
    playstyle: "Slow squeeze, technical endings, and low-risk positional pressure.",
    oneYearScore: [81, 82, 83, 84, 85, 85, 86, 86],
  },
  {
    id: "clockwork-tess",
    handle: "Clockwork",
    realName: "Tess de Vries",
    country: "Netherlands",
    countryCode: "nl",
    game: "Rocket League",
    role: "Striker",
    rank: 14,
    score: 85,
    trend: 4,
    identity: "Mechanical Demon",
    aura: "The Gearshift",
    bestMap: "Mannfield",
    strengths: ["First touch", "Aerial mechanics", "Boost efficiency"],
    weakness: "Physical defence",
    summary: "A Dutch striker with tiny adjustments that turn harmless clears into instant danger.",
    playstyle: "Fast aerial control, efficient boost paths, and clean attacking chains.",
    oneYearScore: [72, 75, 78, 80, 82, 84, 85, 85],
  },
  {
    id: "ember-diego",
    handle: "Ember",
    realName: "Diego Santos",
    country: "Brazil",
    countryCode: "br",
    game: "Valorant",
    role: "Duelist",
    rank: 15,
    score: 84,
    trend: 4,
    identity: "Chaos Agent",
    aura: "The Bonfire",
    bestMap: "Split",
    strengths: ["Entry creativity", "Mid-round aggression", "Confidence"],
    weakness: "Overheating in anti-ecos",
    summary: "A duelist who wants every round to become a street festival with crossfires.",
    playstyle: "Creative entries, sudden flanks, and fearless close-range pressure.",
    oneYearScore: [70, 72, 75, 78, 80, 82, 83, 84],
  },
  {
    id: "lumen-hana",
    handle: "Lumen",
    realName: "Hana Park",
    country: "South Korea",
    countryCode: "kr",
    game: "League of Legends",
    role: "Support",
    rank: 16,
    score: 83,
    trend: 2,
    identity: "Team Anchor",
    aura: "The Lantern",
    bestMap: "Summoner's Rift",
    strengths: ["Vision webs", "Engage timing", "Lane protection"],
    weakness: "Low roaming risk",
    summary: "A support who keeps the map lit and the carries breathing.",
    playstyle: "Vision control, controlled engages, and carry-first protection.",
    oneYearScore: [75, 77, 78, 80, 81, 82, 83, 83],
  },
  {
    id: "rift-noah",
    handle: "Rift",
    realName: "Noah Johnson",
    country: "USA",
    countryCode: "us",
    game: "Fortnite",
    role: "Builder",
    rank: 17,
    score: 82,
    trend: 3,
    identity: "Creative Builder",
    aura: "The Skybridge",
    bestMap: "Moving Zone",
    strengths: ["Retakes", "Piece pressure", "Fast edits"],
    weakness: "Storm surge planning",
    summary: "A builder who sees vertical space as a second inventory.",
    playstyle: "Edit speed, vertical retakes, and aggressive box pressure.",
    oneYearScore: [73, 74, 76, 78, 79, 80, 81, 82],
  },
  {
    id: "veloce-antoine",
    handle: "Veloce",
    realName: "Antoine Martin",
    country: "France",
    countryCode: "fr",
    game: "Rocket League",
    role: "Support",
    rank: 18,
    score: 81,
    trend: 1,
    identity: "Silent Carry",
    aura: "The Second Touch",
    bestMap: "DFH Stadium",
    strengths: ["Recovery speed", "Pass selection", "Defensive reads"],
    weakness: "Needs more shooting volume",
    summary: "A quiet Rocket League support whose second touch decides whether a team looks brilliant.",
    playstyle: "Fast recoveries, passing lanes, and stabilising rotations.",
    oneYearScore: [76, 76, 78, 79, 80, 80, 81, 81],
  },
  {
    id: "vertex-kai",
    handle: "Vertex",
    realName: "Kai Sato",
    country: "Japan",
    countryCode: "jp",
    game: "Chess",
    role: "Strategist",
    rank: 19,
    score: 80,
    trend: 2,
    identity: "Macro Architect",
    aura: "The Diagram",
    bestMap: "Queen's Gambit",
    strengths: ["Opening prep", "Pattern memory", "Endgame patience"],
    weakness: "Time trouble in wild positions",
    summary: "A strategist with clean preparation and a gift for quiet traps.",
    playstyle: "Prepared openings, long squeezes, and patient conversion.",
    oneYearScore: [72, 74, 75, 76, 78, 79, 80, 80],
  },
  {
    id: "spark-marta",
    handle: "Spark",
    realName: "Marta Kowalska",
    country: "Poland",
    countryCode: "pl",
    game: "CS2",
    role: "Support",
    rank: 20,
    score: 79,
    trend: 2,
    identity: "Team Anchor",
    aura: "The Rivet",
    bestMap: "Overpass",
    strengths: ["Flash assists", "Trade spacing", "Site anchoring"],
    weakness: "Limited star roles",
    summary: "A support who wins the invisible parts of the round.",
    playstyle: "Flash timing, disciplined anchors, and trade-first spacing.",
    oneYearScore: [70, 71, 73, 75, 76, 78, 79, 79],
  },
  {
    id: "pulse-alejandro",
    handle: "Pulse",
    realName: "Alejandro García",
    country: "Spain",
    countryCode: "es",
    game: "Valorant",
    role: "Controller",
    rank: 21,
    score: 78,
    trend: 4,
    identity: "Momentum Player",
    aura: "The Sparkplug",
    bestMap: "Pearl",
    strengths: ["Smoke bursts", "Retake timing", "Emotional tempo"],
    weakness: "Over-rotating",
    summary: "A controller with rhythm who changes the speed of the round.",
    playstyle: "Fast utility bursts, retake orchestration, and tempo shifts.",
    oneYearScore: [66, 69, 72, 74, 76, 77, 78, 78],
  },
  {
    id: "echo-thabo",
    handle: "Echo",
    realName: "Thabo Ndlovu",
    country: "South Africa",
    countryCode: "za",
    game: "CS2",
    role: "IGL",
    rank: 22,
    score: 77,
    trend: 6,
    identity: "Tactical Brain",
    aura: "The Vanguard",
    bestMap: "Anubis",
    strengths: ["Anti-strats", "Resilience", "Regional leadership"],
    weakness: "International reps",
    summary: "An IGL building a map from the edge of the scene.",
    playstyle: "Prepared calls, adaptive defaults, and late-round problem solving.",
    oneYearScore: [60, 64, 68, 71, 73, 75, 76, 77],
  },
  {
    id: "meteor-faris",
    handle: "Meteor",
    realName: "Faris Al-Saud",
    country: "Saudi Arabia",
    countryCode: "sa",
    game: "Rocket League",
    role: "Striker",
    rank: 23,
    score: 76,
    trend: 7,
    identity: "Momentum Player",
    aura: "The Sandstorm",
    bestMap: "Utopia Coliseum",
    strengths: ["Aerial speed", "Solo plays", "Confidence"],
    weakness: "Defensive patience",
    summary: "A rising striker who makes every aerial look like a statement.",
    playstyle: "Fast challenges, solo aerial pressure, and aggressive shooting windows.",
    oneYearScore: [56, 60, 65, 69, 72, 74, 75, 76],
  },
  {
    id: "signalflare-amina",
    handle: "Signalflare",
    realName: "Amina Adebayo",
    country: "Nigeria",
    countryCode: "ng",
    game: "Fortnite",
    role: "Builder",
    rank: 24,
    score: 75,
    trend: 8,
    identity: "Creative Builder",
    aura: "The Signalflare",
    bestMap: "Final Circle",
    strengths: ["Mobile mechanics", "Adaptability", "Community energy"],
    weakness: "Tournament infrastructure",
    summary: "A rising builder shaped by creativity over comfort.",
    playstyle: "Improvised builds, fast edits, and survival-first endgames.",
    oneYearScore: [52, 57, 62, 67, 71, 73, 74, 75],
  },
  {
    id: "gambit-sofia",
    handle: "Gambit",
    realName: "Sofia Rivera",
    country: "Mexico",
    countryCode: "mx",
    game: "Chess",
    role: "Strategist",
    rank: 25,
    score: 74,
    trend: 4,
    identity: "Clutch Artist",
    aura: "The Trapdoor",
    bestMap: "King's Indian",
    strengths: ["Tactical traps", "Time pressure", "Counterplay"],
    weakness: "Passive endgames",
    summary: "A strategist who enjoys positions with teeth.",
    playstyle: "Counter-attacks, tactical baiting, and sharp middle games.",
    oneYearScore: [63, 65, 67, 69, 71, 72, 74, 74],
  },
  {
    id: "anchor-liam",
    handle: "Anchor",
    realName: "Liam Wilson",
    country: "New Zealand",
    countryCode: "nz",
    game: "Rocket League",
    role: "Support",
    rank: 26,
    score: 73,
    trend: 2,
    identity: "Team Anchor",
    aura: "The Keel",
    bestMap: "Aquadome",
    strengths: ["Defensive rotations", "Clears", "Composure"],
    weakness: "Limited offensive pressure",
    summary: "A steady support who turns panic into reset and reset into counterattack.",
    playstyle: "Safe rotations, recovery defence, and patient counter-play.",
    oneYearScore: [66, 67, 68, 70, 71, 72, 73, 73],
  },
  {
    id: "rhythm-sofia",
    handle: "Rhythm",
    realName: "Sofia Silva",
    country: "Argentina",
    countryCode: "ar",
    game: "Fortnite",
    role: "Builder",
    rank: 27,
    score: 72,
    trend: 3,
    identity: "Creative Builder",
    aura: "The Tango",
    bestMap: "Box Fight",
    strengths: ["Edit rhythm", "Close-range fights", "Improvisation"],
    weakness: "Long rotation planning",
    summary: "A creative builder with musical timing and close-range danger.",
    playstyle: "Fast box edits, reactive building, and short-range pressure.",
    oneYearScore: [62, 64, 66, 68, 70, 71, 72, 72],
  },
  {
    id: "lantern-nils",
    handle: "Lantern",
    realName: "Nils Eriksen",
    country: "Norway",
    countryCode: "no",
    game: "CS2",
    role: "Support",
    rank: 28,
    score: 71,
    trend: 2,
    identity: "Silent Carry",
    aura: "The Northern Light",
    bestMap: "Vertigo",
    strengths: ["Flash timing", "Calm comms", "Retake support"],
    weakness: "Low duel volume",
    summary: "A support whose value appears in the scoreboard margins.",
    playstyle: "Careful utility, calm retakes, and low-noise impact.",
    oneYearScore: [64, 65, 66, 68, 69, 70, 71, 71],
  },
  {
    id: "circuit-mei",
    handle: "Circuit",
    realName: "Mei Lin",
    country: "Taiwan",
    countryCode: "tw",
    game: "League of Legends",
    role: "Mid Laner",
    rank: 29,
    score: 70,
    trend: 2,
    identity: "Macro Architect",
    aura: "The Circuit",
    bestMap: "Summoner's Rift",
    strengths: ["Wave control", "Side-lane timing", "Scaling plans"],
    weakness: "Early skirmish volatility",
    summary: "A mid laner who likes clean circuits: wave, ward, rotate, repeat.",
    playstyle: "Scaling lanes, rotation discipline, and calculated side pressure.",
    oneYearScore: [62, 64, 65, 67, 68, 69, 70, 70],
  },
  {
    id: "onyx-omar",
    handle: "Onyx",
    realName: "Omar Hassan",
    country: "Egypt",
    countryCode: "eg",
    game: "Valorant",
    role: "Controller",
    rank: 30,
    score: 69,
    trend: 5,
    identity: "Team Anchor",
    aura: "The Obelisk",
    bestMap: "Sunset",
    strengths: ["Site control", "Post-plants", "Utility patience"],
    weakness: "Opening map pressure",
    summary: "A controller who gives every round a spine.",
    playstyle: "Post-plant control, site denial, and patience under pressure.",
    oneYearScore: [55, 58, 61, 64, 66, 68, 69, 69],
  }
];
